name: Deploy Front

on:
  workflow_dispatch:

jobs:
  deploy_front:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'



    steps:

    - uses: 'actions/checkout@v4'


    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'my-project'
        credentials_json: '${{ secrets.GCP_SA_KEY }}'


    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build

    - name: 'deploy front AppEngine'
      uses: 'google-github-actions/deploy-appengine@v2'
      with:
        working_directory: 'front'
    